local_fs: xfs
enable_nfs: 'yes'
local_dns_lookup: 'no'
enable_gridengine: 'no'
enable_slurm: 'yes'
use_master_as_compute: 'no'
enable_zabbix: 'no'
enable_ide: 'no'
nfs_mounts:
- src: /vol/spool
  dst: /vol/spool
ext_nfs_mounts: []
slurmConf:
  db: slurm
  db_user: slurm
  db_password: changeme
ansible_galaxy_roles:
- name: autoscaling
  hosts: master
  git: https://github.com/patricS4/autoscaling-config-ansible
