---
- name: Update apt cache
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install xfce4
  ansible.builtin.apt:
    name: xfce4*
    state: present

- name: Remove snap Firefox
  become: true
  snap:
    name: firefox
    state: absent


- name: Ensure software-properties-common is installed
  become: true
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: Add MozillaTeam PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
    state: present
    update_cache: true

- name: Configure APT pinning for Mozilla Firefox
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/mozilla-firefox
    content: |
      Package: firefox*
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 501

- name: Install Firefox from APT
  become: true
  ansible.builtin.apt:
    name: firefox
    state: latest
    update_cache: true

- name: Install TigerVNC Server
  become: true
  ansible.builtin.apt:
    name: tigervnc-standalone-server
    state: latest
    update_cache: true

- name: Ensure .vnc directory exists for ubuntu user
  file:
    path: /home/ubuntu/.vnc
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0700"

- name: Set VNC password
  ansible.builtin.shell: "echo 'ubuntu' | vncpasswd -f > /home/ubuntu/.vnc/passwd"


- name: Deploy xstartup script for ubuntu user
  copy:
    src: files/xstartup
    dest: /home/ubuntu/.vnc/xstartup
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Deploy vnc-server service
  become: true
  ansible.builtin.template:
    src: vncserver@.service.j2
    dest: /etc/systemd/system/vncserver@.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to pick up new units
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable vncserver@ubuntu.service at boot
  ansible.builtin.systemd:
    name: vncserver@ubuntu
    enabled: yes

