---
- name: Install theia_ide role
  block:

    - name: Install build packages on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - python3
          - make
          - g++
          - curl
          - git
          - pkg-config
          - libx11-dev
          - libxkbfile-dev
          - libsecret-1-dev
          - libgtk-3-dev
          - libnss3-dev
          - libasound2-dev
          - libxss1
        state: present
        update_cache: yes
      when: ansible_distribution_file_variety == 'Debian'

    - name: Install build packages on RedHat/CentOS
      ansible.builtin.yum:
        name:
          - python3
          - curl
          - git
          - make
          - gcc
          - gcc-c++
          - pkgconfig
          - libX11-devel
          - libxkbfile-devel
          - libsecret-devel
          - gtk3-devel
          - nss-devel
          - alsa-lib-devel
        state: present
      when: ansible_distribution_file_variety == 'RedHat'
      
    - name: Create NVM install dir
      file:
        path: "{{ theiaide_vars.NVM_INSTALL_DIR }}"
        state: directory
        owner: "{{ theiaide_vars.THEIA_USER }}"
        group: "{{ theiaide_vars.THEIA_USER }}"
        mode: "0755"

    - name: Set fact 'theia_ide_workspace' to '${HOME}'
      ansible.builtin.set_fact:
        theia_ide_workspace: "/home/{{ theiaide_vars.THEIA_USER }}"

    - name: Install nvm
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | NVM_DIR={{ theiaide_vars.NVM_INSTALL_DIR }} bash
      args:
        creates: "{{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh"
      environment:
        HOME: "{{ theia_ide_workspace }}"
      become_user: "{{ theiaide_vars.THEIA_USER }}"

    - name: Install Node.js 22 via NVM
      ansible.builtin.shell: |
        source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh
        nvm install 22
        nvm use 22
        npm install -g yarn
      args:
        executable: /bin/bash
      become_user: "{{ theiaide_vars.THEIA_USER }}"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ theiaide_vars.THEIA_USER }}"
        mode: "0755"
      loop:
        - "{{ theiaide_vars.THEIA_INSTALL_DIR  }}"

    - name: Clone Theia repository
      ansible.builtin.git:
        repo: "{{ theiaide_vars.THEIA_REPO }}"
        dest: "{{ theiaide_vars.THEIA_INSTALL_DIR  }}"
        version: "{{ theiaide_vars.THEIA_VERSION }}"
        force: yes
        update: yes
        accept_hostkey: yes
        clone: yes
      become_user: "{{ theiaide_vars.THEIA_USER }}"

    - name: Install Node dependencies
      ansible.builtin.shell: |
        source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh
        export GITHUB_TOKEN="{{ github_token }}"
        yarn
        yarn build
        yarn download:plugins
      args:
        chdir: "{{ theiaide_vars.THEIA_INSTALL_DIR  }}"
        executable: /bin/bash
      become_user: "{{ theiaide_vars.THEIA_USER }}"

    - name: Create theia systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/theia.service
        content: |
          [Unit]
          Description=Theia IDE
          After=network.target

          [Service]
          User={{ theiaide_vars.THEIA_USER }}
          WorkingDirectory={{ theiaide_vars.THEIA_INSTALL_DIR }}
          ExecStart=/bin/bash -lc "yarn browser start --hostname {{ theiaide_vars.THEIA_BIND_ADDRESS }} --port {{ theiaide_vars.THEIA_BIND_PORT }}"
          Restart=always
          Environment=HOME={{ theiaide_vars.THEIA_INSTALL_DIR }}

          # Hardening
          NoNewPrivileges=true
          ProtectSystem=strict
          ProtectHome=true
          PrivateTmp=true

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Theia
      ansible.builtin.systemd:
        name: theia
        state: started
        enabled: yes
        daemon_reload: yes

  when: not theiaide_vars.create_only_backend
