---
- name: Install theia_ide role
  block:
    - name: Install packages
      ansible.builtin.apt:
        name: [python3, make, g++, curl, git]
      when: ansible_distribution_file_variety == 'Debian'

    - name: install packages
      yum:
        name: [python3, curl, git, make, gcc, gcc-c++]
      when: ansible_distribution_file_variety == 'RedHat'

    - name: Create NVM install dir
      ansible.builtin.file:
        path: "{{ theiaide_vars.NVM_INSTALL_DIR }}"
        state: directory
        mode: "0755"

    - name: Set fact 'theia_ide_user' when not defined
      ansible.builtin.set_fact:
        theia_ide_user: "{{ ansible_env.SUDO_USER }}"
      when: theia_ide_user is not defined

    - name: Set fact 'theia_ide_workspace' to '${HOME}'
      ansible.builtin.set_fact:
        theia_ide_workspace: ${HOME}

    - name: Install nvm
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.3/install.sh | NVM_DIR={{ theiaide_vars.NVM_INSTALL_DIR }} /bin/bash
      args:
        creates: "{{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh"

    - name: Install node 122 and yarn
      ansible.builtin.shell: |
        source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh
        nvm install 22
        npm install -g yarn
      args:
        executable: bash


    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ theia_user }}"
        mode: "0755"
      loop:
        - "{{ theia_install_dir }}"
        - "{{ theia_workspace }}"

    - name: Clone Theia repository
      git:
        repo: "{{ theia_repo }}"
        dest: "{{ theia_install_dir }}"
        version: "{{ theia_version }}"
        force: yes
        update: yes
        accept_hostkey: yes
        clone: yes
      become_user: "{{ theia_user }}"

    - name: Install Node dependencies
      shell: |
        yarn
        yarn build
        yarn download:plugins
      args:
        chdir: "{{ theia_install_dir }}"
      become_user: "{{ theia_user }}"


    - name: Create theia systemd service
      copy:
        dest: /etc/systemd/system/theia.service
        content: |
          [Unit]
          Description=Theia IDE
          After=network.target

          [Service]
          User=theia
          WorkingDirectory=/srv/theia
          ExecStart=/usr/bin/node /opt/theia/packages/browser/src-gen/backend/main.js --hostname 0.0.0.0 --port 8080
          Restart=always
          Environment=HOME=/srv/theia

          # Hardening
          NoNewPrivileges=true
          ProtectSystem=strict
          ProtectHome=true
          PrivateTmp=true

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Theia
      systemd:
        name: theia
        state: started
        enabled: yes
        daemon_reload: yes
  when: not theiaide_vars.create_only_backend
