---
- name: Install theia_ide role
  block:

    - name: Install build packages on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - python3
          - make
          - g++
          - curl
          - git
          - pkg-config
          - libx11-dev
          - libxkbfile-dev
          - libsecret-1-dev
          - libgtk-3-dev
          - libnss3-dev
          - libasound2-dev
          - libxss1
        state: present
        update_cache: yes
      when: ansible_distribution_file_variety == 'Debian'

    - name: Install build packages on RedHat/CentOS
      ansible.builtin.yum:
        name:
          - python3
          - curl
          - git
          - make
          - gcc
          - gcc-c++
          - pkgconfig
          - libX11-devel
          - libxkbfile-devel
          - libsecret-devel
          - gtk3-devel
          - nss-devel
          - alsa-lib-devel
        state: present
      when: ansible_distribution_file_variety == 'RedHat'
    - name: Create NVM install dir
      ansible.builtin.file:
        path: "{{ theiaide_vars.NVM_INSTALL_DIR }}"
        state: directory
        mode: "0755"
      become_user: "{{ theia_ide_user }}"
    - name: Set fact 'theia_ide_user' when not defined
      ansible.builtin.set_fact:
        theia_ide_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      when: theia_ide_user is not defined

    - name: Set fact 'theia_ide_workspace' to '${HOME}'
      ansible.builtin.set_fact:
        theia_ide_workspace: "{{ lookup('env','HOME') }}"

    - name: Install nvm
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | NVM_DIR={{ theiaide_vars.NVM_INSTALL_DIR }} bash
      args:
        creates: "{{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh"
      environment:
        HOME: "{{ theia_ide_workspace }}"
      become_user: "{{ theia_ide_user }}"

    - name: Install Node.js 22 via NVM
      ansible.builtin.shell: |
        source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh
        nvm install 22
        nvm use 22
        npm install -g yarn
      args:
        executable: /bin/bash
      become_user: "{{ theia_ide_user }}"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ theia_ide_user }}"
        mode: "0755"
      loop:
        - "{{ theia_install_dir }}"
        - "{{ theia_workspace }}"

    - name: Clone Theia repository
      ansible.builtin.git:
        repo: "{{ theia_repo }}"
        dest: "{{ theia_install_dir }}"
        version: "{{ theia_version }}"
        force: yes
        update: yes
        accept_hostkey: yes
        clone: yes
      become_user: "{{ theia_ide_user }}"

    - name: Install Node dependencies
      ansible.builtin.shell: |
        source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh
        yarn
        yarn build
        yarn download:plugins
      args:
        chdir: "{{ theia_install_dir }}"
        executable: /bin/bash
      become_user: "{{ theia_ide_user }}"

    - name: Create theia systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/theia.service
        content: |
          [Unit]
          Description=Theia IDE
          After=network.target

          [Service]
          User={{ theia_ide_user }}
          WorkingDirectory={{ theia_install_dir }}
          ExecStart=/bin/bash -c 'source {{ theiaide_vars.NVM_INSTALL_DIR }}/nvm.sh && yarn browser start --hostname 0.0.0.0 --port 8080'
          Restart=always
          Environment=HOME={{ theia_ide_workspace }}

          # Hardening
          NoNewPrivileges=true
          ProtectSystem=strict
          ProtectHome=true
          PrivateTmp=true

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Theia
      ansible.builtin.systemd:
        name: theia
        state: started
        enabled: yes
        daemon_reload: yes

  when: not theiaide_vars.create_only_backend
