---
- name: Install Theia IDE (AppImage) as systemd service
  hosts: all
  become: yes

  vars:
    theia_version: "1.67.0"
    theia_user: ubuntu
    theia_port: 8080
    theia_dir: /opt/theia
    theia_bin: /opt/theia/theia.AppImage

    theia_appimage_url: "https://github.com/eclipse-theia/theia/releases/download/v{{ theia_version }}/theia-ide-{{ theia_version }}-linux-x86_64.AppImage"

  tasks:

  # -----------------------------
  # Base dependencies
  # -----------------------------
  - name: Install runtime dependencies
    ansible.builtin.apt:
      update_cache: yes
      name:
        - fuse
        - libfuse2
        - curl
        - ca-certificates
      state: present

  # -----------------------------
  # Create directories
  # -----------------------------
  - name: Create Theia directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ theia_user }}"
      group: "{{ theia_user }}"
      mode: "0755"
    loop:
      - "{{ theia_dir }}"
      - "/home/{{ theia_user }}/workspace"
      - "/home/{{ theia_user }}/.theia-ide"

  # -----------------------------
  # Download AppImage
  # -----------------------------
  - name: Download Theia AppImage
    ansible.builtin.get_url:
      url: "{{ theia_appimage_url }}"
      dest: "{{ theia_bin }}"
      mode: "0755"
      force: yes

  # -----------------------------
  # Extract AppImage (server-safe mode)
  # -----------------------------
  - name: Extract AppImage
    ansible.builtin.command: "{{ theia_bin }} --appimage-extract"
    args:
      chdir: "{{ theia_dir }}"
      creates: "{{ theia_dir }}/squashfs-root"

  # -----------------------------
  # Create systemd service
  # -----------------------------
  - name: Create Theia systemd service
    ansible.builtin.copy:
      dest: /etc/systemd/system/theia.service
      mode: "0644"
      content: |
        [Unit]
        Description=Theia IDE (AppImage Headless)
        After=network.target

        [Service]
        Type=simple
        User={{ theia_user }}
        Environment=HOME=/home/{{ theia_user }}
        WorkingDirectory=/home/{{ theia_user }}
        ExecStart={{ theia_dir }}/squashfs-root/AppRun \
          --hostname 0.0.0.0 \
          --port {{ theia_port }} \
          /home/{{ theia_user }}/workspace
        Restart=always
        RestartSec=5
        LimitNOFILE=100000
        NoNewPrivileges=true
        PrivateTmp=true
        ProtectSystem=full
        ProtectHome=false

        [Install]
        WantedBy=multi-user.target

  # -----------------------------
  # Enable service
  # -----------------------------
  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable and start Theia
    ansible.builtin.systemd:
      name: theia
      enabled: yes
      state: started
