- name: Autoupdate TheiaIDE image
  hosts: localhost

  tasks:
    - set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - set_fact:
        base_images: "{{ images.openstack_image | selectattr('tags', 'search', 'portalclient') | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='2004']"

    - set_fact:
        theiaide_images: "{{ images.openstack_image | selectattr('tags', 'search', 'theiaide') | sort(attribute='created_at') }}"

    - set_fact:
        update: true
        when:
          - base_images | length > 0
          - theiaide_images | length == 0 or
            (theiaide_images | length > 0 and (base_images | last).created_at > (theiaide_images | last).created_at)

    - name: Build new TheiaIDE image
      shell: packer build packer_theiaide_bielefeld.json
      when: update == true




