- name: Autoupdate Guacamole image
  hosts: localhost

  tasks:
    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - set_fact:
        newest_base_image: "{{ images.openstack_image | selectattr('tags', 'search', 'portalclient') | json_query(filter) | sort(attribute='created_at') | last }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='1804']"

    - set_fact:
        newest_guacamole_image: "{{ images.openstack_image | selectattr('tags', 'search', 'guacamole') | sort(attribute='created_at') | last }}"

    - name: Build new Guacamole image
      shell: packer build packer_guacamole_bielefeld.json
      when: newest_base_image.created_at > newest_guacamole_image.created_at




