- name: Autoupdate Guacamole image
  hosts: localhost

  tasks:
    - set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - set_fact:
        base_images: "{{ images.openstack_image | selectattr('tags', 'search', 'portalclient') | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='1804']"

    - set_fact:
        guacamole_images: "{{ images.openstack_image | selectattr('tags', 'search', 'guacamole') | sort(attribute='created_at') }}"

    - set_fact:
        update: true
        when:
          - base_images | length > 0
          - guacamole_images | length == 0 or
            (guacamole_images | length > 0 (base_images | last).created_at > (guacamole_images | last).created_at)

    - name: Build new Guacamole image
      shell: packer build packer_guacamole_bielefeld.json
      when: update == true




