- name: Setting up research environment
  hosts: all
  become: yes
  connection: paramiko_ssh
  gather_facts: yes

  vars:
    resenv:

  tasks:
    - name: Include {{ resenv }} variables
      include_vars:
        file: "packer_{{ resenv }}_vars_file.yml"

    - name: Setting up virtual machine with {{ resenv }}
      import_tasks: "{{ resenv }}.yml"