---
- name: Install geerlingguy.swap role
  ansible.builtin.include_role:
    name: geerlingguy.swap
  vars:
    swap_file_size_mb: "2024"

- name: Download Miniforge
  get_url:
    url: https://github.com/conda-forge/miniforge/releases/download/{{jupyterlab_vars.MINI_FORGE_RELEASE}}/Miniforge3-{{jupyterlab_vars.MINI_FORGE_RELEASE}}-Linux-x86_64.sh
    dest: /tmp/miniforge.sh

- name: Install Miniforge
  command: bash /tmp/miniforge.sh -b -p {{ jupyterlab_vars.CONDA_DIR }}
  args:
    creates: "{{ jupyterlab_vars.CONDA_DIR }}/bin/mamba"

- name: Add Miniforge to PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH={{ jupyterlab_vars.CONDA_DIR }}/bin:$PATH'
  become: true
  become_user: root

- name: Install conda-env role
  include_role:
    name: andrewrothstein.conda-env
  vars:
    conda_env_conda_dir: "{{jupyterlab_vars.CONDA_DIR}}"
    conda_env_name: "{{ jupyterlab_vars.ENV_NAME| quote }}"
    conda_env_environment: "{{ jupyterlab_vars.conda_env_environment_yml}}"
    conda_env_activate_for_login_shell: true

  when: not jupyterlab_vars.create_only_backend

- name: Adjust miniconda folder rights
  become: true
  ansible.builtin.shell: chown -R {{jupyterlab_vars.default_user}}:{{jupyterlab_vars.default_user}} {{jupyterlab_vars.CONDA_DIR}}/
  when: not jupyterlab_vars.create_only_backend

- name: Add bioconda channel
  become_user: "{{   jupyterlab_vars.default_user  }}"
  ansible.builtin.shell: timeout 1m bash -c 'source {{jupyterlab_vars.CONDA_DIR}}/bin/activate && conda config --add channels bioconda'
  args:
    executable: /bin/bash
  when: not jupyterlab_vars.create_only_backend

- name: Add conda-forge channel
  become_user: "{{   jupyterlab_vars.default_user  }}"
  ansible.builtin.shell: timeout 1m bash -c 'source {{jupyterlab_vars.CONDA_DIR}}/bin/activate && conda config --add channels conda-forge'
  args:
    executable: /bin/bash
  when: not jupyterlab_vars.create_only_backend

- name: Init .bashrc for conda
  become_user: "{{   jupyterlab_vars.default_user  }}"
  ansible.builtin.shell: timeout 1m bash -c 'source {{ jupyterlab_vars.CONDA_DIR}}/bin/activate && conda init'
  args:
    executable: /bin/bash
  when: not jupyterlab_vars.create_only_backend

- name: Create alias for environment
  become_user: "{{   jupyterlab_vars.default_user  }}"
  ansible.builtin.shell: echo $ALIAS_VARIABLE > ~/.bash_aliases
  environment:
    ALIAS_VARIABLE: alias {{ jupyterlab_vars.ENV_NAME| quote }}="conda activate {{ jupyterlab_vars.ENV_NAME| quote }}"
  when: not jupyterlab_vars.create_only_backend

- name: Set facts for templates
  ansible.builtin.set_fact:
    jupyterlab_conda_dir: "{{jupyterlab_vars.CONDA_DIR}}"
    jupyterlab_env_name: "{{ jupyterlab_vars.ENV_NAME}}"
    jupyterlab_default_user: "{{ jupyterlab_vars.default_user  }}"
    jupyterlab_base_url: "{{ jupyterlab_vars.base_url }}"
- name: Generate systemd service
  ansible.builtin.template:
    src: ./templates/jupyterlab.service.j2
    dest: /lib/systemd/system/jupyter-lab.service
    mode: "0644"
    force: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start  JupyterLab Service
  ansible.builtin.systemd:
    name: jupyter-lab
    state: restarted
    enabled: true
