---
- ansible.builtin.debug:
    msg: "[BIBIGRID] Setup Slurm"
- name: Create Slurm group
  ansible.builtin.group:
    name: slurm
    gid: 64030

- name: Create Slurm user
  ansible.builtin.user:
    name: slurm
    uid: 64030
    group: slurm

- name: Install Slurm package (and dependencies)
  ansible.builtin.apt:
    name:
      - slurm-full
      - munge

- name: Install Python package
  ansible.builtin.pip:
    name: shortuuid

- name: Generate munge key
  command: python -c "import uuid; print(str(uuid.uuid4()))"
  register: munge_key_output
  changed_when: false



- name: Create new secret (Munge)
  ansible.builtin.copy:
    content: '{{ munge_key_output.stdout }}'
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600
  notify:
    - munge

- name: Ensures slurm directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: slurm

  with_items:
    - /etc/slurm
    - /var/lib/slurm
    - /var/log/slurm

- name: Create system overrides directories (slurmd, slurmctld)
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    group: root
    owner: root
    mode: "0755"
    state: directory
  with_items:
    - slurmd
    - slurmctld

- name: Copy system overrides (slurmd, slurmctld)
  ansible.builtin.copy:
    src: "slurm/systemd/{{ item }}.override"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - slurmd
    - slurmctld
  notify:
    - slurmd
    - slurmctld

- name: Enable slurmctld and slurmd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
    daemon_reload: true
  with_items:
    - slurmctld
    - slurmd

- name: Create Slurm configuration
  ansible.builtin.template:
    src: ./files/slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd

- name: Slurm cgroup configuration
  ansible.builtin.copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd
