- name: Setup Slurm
  block:
    - ansible.builtin.debug:
        msg: "[BIBIGRID] Setup Slurm"
    - ansible.builtin.import_tasks: 042-slurm.yml
    - ansible.builtin.import_tasks: 042-slurm-server.yml
      tags: master
