---
- name: Wait for automatic system updates 1
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
  when: not cwlab_vars.create_only_backend

- name: Wait for automatic system updates 2
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;
  when: not cwlab_vars.create_only_backend

- name: Generate distribution information
  ansible.builtin.command: lsb_release -cs
  register: release

- name: Install python3-pip
  ansible.builtin.apt:
    state: latest
    update: true
    upgrade: true
    name: python3-pip
  when: not cwlab_vars.create_only_backend

- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip3
    state: latest
  when: not cwlab_vars.create_only_backend

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: not cwlab_vars.create_only_backend

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
    state: present
  when: not cwlab_vars.create_only_backend

- name: Update apt and install docker-ce
  ansible.builtin.apt: update_cache=yes name=docker-ce state=latest
  when: not cwlab_vars.create_only_backend

- name: Install Docker Module for Python
  pip:
    name: docker
  when: not cwlab_vars.create_only_backend

- name: Install Setuptools
  apt:
    name: python3-setuptools
    update: true
    upgrade: true
  when: not cwlab_vars.create_only_backend

- name: Install Docker Compose Module for Python
  pip:
    name: docker-compose
  when: not cwlab_vars.create_only_backend

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  become: true
  when: not cwlab_vars.create_only_backend


- name: Install docker python dev package
  ansible.builtin.apt:
    name: python3-docker
    update: true
    upgrade: true
    state: latest
  become: true
  when: not cwlab_vars.create_only_backend

- name: Ensure data path exists
  ansible.builtin.file:
    state: directory
    path: "{{ cwlab_vars.data_volume_path }}"
    recurse: true
    owner: ubuntu
    group: ubuntu
  when: not cwlab_vars.create_only_backend

- name: Launch cwlab container
  community.general.docker_container:
    name: cwlab
    image: "{{ cwlab_vars.image }}"
    ports:
      - "{{ cwlab_vars.exposed_port }}:5000"
    volumes:
      - "{{ cwlab_vars.data_volume_path }}:/cwlab"
    restart_policy: always
    user: 1000:1000
    recreate: true
    privileged: true
    working_dir: /cwlab
    container_default_behavior: no_defaults
  when: not cwlab_vars.create_only_backend
