---
- name: Install python3-pip
  ansible.builtin.apt:
    state: latest
    update_cache: true
    name: python3-pip
  when: not cwlab_vars.create_only_backend

- name: install the package, force upgrade
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest
  when: not cwlab_vars.create_only_backend


- name: Install docker role
  include_role:
    name: geerlingguy.docker
  when: not cwlab_vars.create_only_backend


- name: Install Setuptools
  ansible.builtin.apt:
    name: python3-setuptools
    update_cache: true
  when: not cwlab_vars.create_only_backend

- name: Install Docker Compose Module for Python
  ansible.builtin.pip:
    name: docker-compose
  when: not cwlab_vars.create_only_backend

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  become: true
  when: not cwlab_vars.create_only_backend


- name: Install docker python dev package
  ansible.builtin.apt:
    name: python3-docker
    update_cache: true
    state: latest
  become: true
  when: not cwlab_vars.create_only_backend

- name: Ensure data path exists
  ansible.builtin.file:
    state: directory
    path: "{{ cwlab_vars.data_volume_path }}"
    recurse: true
    owner: ubuntu
    group: ubuntu
  when: not cwlab_vars.create_only_backend

- name: Launch cwlab container
  community.general.docker_container:
    name: cwlab
    image: "{{ cwlab_vars.image }}"
    ports:
      - "{{ cwlab_vars.exposed_port }}:5000"
    volumes:
      - "{{ cwlab_vars.data_volume_path }}:/cwlab"
    restart_policy: always
    user: 1000:1000
    recreate: true
    privileged: true
    working_dir: /cwlab
    container_default_behavior: no_defaults
  when: not cwlab_vars.create_only_backend
