- name: Install guacamole role
  include_role:
    name: guacamole
  when: guacamole_vars.create_only_backend == "false"

- name: Flush guacamole handlers
  meta: flush_handlers
  when: guacamole_vars.create_only_backend == "false"

- name: Setup password  for default ubuntu user - standart
  ansible.builtin.user:
    name: "{{ guacamole_vars.default_user }}"
    password: "{{ guacamole_vars.default_password | password_hash('sha512') }}"
  when: guacamole_vars.create_only_backend == "true"

- name: Restart xrdp
  systemd:
    name: xrdp
    state: restarted
  when: guacamole_vars.create_only_backend == "true"

- name: Restart guacd
  systemd:
    name: guacd
    state: restarted
  when: guacamole_vars.create_only_backend == "true"

- name: Restart Tomcat
  systemd:
    name: tomcat9
    state: restarted
  when: guacamole_vars.create_only_backend == "true"

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: guacamole_vars.create_only_backend == "true"

