---
- name: Install guacamole role
  ansible.builtin.include_role:
    name: guacamole
  when: not guacamole_vars.create_only_backend

- name: Flush guacamole handlers
  ansible.builtin.meta: flush_handlers
  when: not guacamole_vars.create_only_backend

- name: Setup password  for default ubuntu user - standart
  ansible.builtin.user:
    name: "{{ guacamole_vars.default_user }}"
    password: "{{ guacamole_vars.default_password | password_hash('sha512') }}"
  when: not guacamole_vars.create_only_backend

- name: Restart xrdp
  ansible.builtin.systemd:
    name: xrdp
    enabled: true
    state: restarted
  when: not guacamole_vars.create_only_backend

- name: Restart guacd
  ansible.builtin.systemd:
    name: guacd
    enabled: true
    state: restarted
  when: not guacamole_vars.create_only_backend

- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat9
    enabled: true
    state: restarted
  when: not guacamole_vars.create_only_backend

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: not guacamole_vars.create_only_backend
