---
# vars file for guacamolerdp-ansible

default_user: ubuntu
default_password: ogvkyf
# you can create password hashes like here https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible
default_password_hashed: $6$iRrIJogrR0N2ZVdb$oL5XzFqcTC.O3g4DS945a5K7nRvO0LqY.ugyjDINUA347qRYXe1YXag8cRlLf9PVwmNrRYU3LTNGyCIPbFvz4/
guac_user: denbi
guac_password: denbi
guacamole_version: 1.4.0
