- hosts: localhost
  become: 'yes'
  vars_files:
  - vars/common_configuration.yml
  roles:
  - geerlingguy.docker
  - common
  - master
  - role: slurm
    tags:
    - slurm
    - scale-up
    - scale-down
    - autoscaling
