---
- name: Cluster Master Setup
  hosts: all
  become: true
  vars_files:
    - vars/common_configuration.yml
  roles:
    - common
    - master
    - role: slurm
      tags:
        - master
        - slurm
        - scale-up
        - scale-down
        - autoscaling
    - autoscaling
