---
- hosts: master
  name: Cluster Master Setup
  become: true
  vars_files:
    - vars/common_configuration.yml
  roles:
    - common
    - master
    - role: slurm
      tags:
        - slurm
        - scale-up
        - scale-down
        - autoscaling
- hosts: workers
  name: Cluster Worker Setup
  become: true
  vars_files:
    - vars/common_configuration.yml
  roles:
    - common
    - worker
    - role: slurm
      tags:
        - slurm
        - scale-up
        - scale-down
