---
- hosts: all
  name: Cluster Worker Setup
  become: "yes"
  vars_files:
    - vars/common_configuration.yml
  roles:
    - common
    - geerlingguy.docker
    - worker
    - role: slurm
      tags:
        - slurm
        - scale-up
        - scale-down
