---
- name: Cluster Worker Setup
  hosts: all
  become: true
  vars_files:
    - vars/common_configuration.yml
  roles:
    - common
    - worker
    - role: slurm
      tags:
        - slurm
        - scale-up
        - scale-down
