- name: Debian based system
  debug:
    msg: Using apt to install packages

- name: Disable auto-update/upgrade during ansible-run
  copy:
    src: disable-auto-upgrades.conf
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Wait till Apt_Mirror de.NBI Bielefeld Service is done
  ansible.builtin.service_facts:
  until: services['de.NBI_Bielefeld_environment.service'].state == 'stopped'
  retries: 35
  delay: 10
  when: services['de.NBI_Bielefeld_environment.service'] is defined

- name: Update
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: Install common packages
  apt:
    name: ["apt-transport-https","ca-certificates","curl","software-properties-common","python3-pip","python3-setuptools"]
    state: "present"

- name: Install OpenStack object store client
  apt:
    name: "swift"
    state: "present"
  when: mode == "openstack"

- name: Add Docker repository key
  apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    state: present

- name: Add Docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename}} stable'
    state: present

- name: Add zabbix repositories
  apt:
    deb: 'https://repo.zabbix.com/zabbix/5.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ ansible_distribution_release }}_all.deb'
    state: present

- name: Add apt.bi.denbi.de repository key
  apt_key:
    url: 'https://apt.bi.denbi.de/repo_key.key'
    state: present

- name: Add apt.bi.denbi.de repository
  apt_repository:
    repo: 'deb https://apt.bi.denbi.de/repos/apt/{{ ansible_distribution_release | lower }} {{ ansible_distribution_release | lower }} main'

- name: Update apt cache
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    cache_valid_time: 86400 #One day
