---
- name: Install zabbix python-api
  ansible.builtin.pip:
    name: zabbix-api

- name: Install zabbix agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: latest
  when: ansible_distribution_file_variety == 'Debian'

- name: Install zabbix agent
  ansible.builtin.dnf:
    name: zabbix-agent
    state: latest
  when: ansible_distribution_file_variety == 'RedHat'

- name: Create zabbix_agent dropin directory
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agentd.d/
    state: directory
    mode: 0755

- name: Create zabbix_agent log directory
  ansible.builtin.file:
    path: /var/log/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: Adjust zabbix agent configuration
  ansible.builtin.template:
    src: zabbix/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Restart zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: true
