---
- name: Generate directory structure available on all hosts
  ansible.builtin.file:
    path: /etc/bibigrid
    state: directory
    owner: root
    group: "{{ ansible_distribution | lower }}"
    mode: 0775
