---
- name: Common dependencies - debian
  when: ansible_distribution_file_variety == 'Debian'
  tags:
    - pkg
    - common-pkg
  block:
    - ansible.builtin.debug:
        msg: "[BIBIGRID] Setup common software and dependencies"
    - ansible.builtin.import_tasks: 001-apt.yml


- name: Common dependencies - RedHat
  when: ansible_distribution_file_variety == 'RedHat'
  tags:
    - pkg
    - common-pkg
  block:
    - ansible.builtin.debug:
        msg: "[BIBIGRID] Setup common software and dependencies"
    - ansible.builtin.import_tasks: 001-yum.yml

- ansible.builtin.debug:
    msg: "[BIBIGRID] Generate directory structure available on all hosts"
- ansible.builtin.import_tasks: 020-disk.yml
  tags:
    - pkg
    - common-pkg
