- block:
  - debug:
      msg: "[BIBIGRID] Setup common software and dependencies"
  - include: 001-apt.yml
  tags: ["pkg","common-pkg"]
  when: "ansible_distribution_file_variety == 'Debian'"

- block:
  - debug:
      msg: "[BIBIGRID] Setup common software and dependencies"
  - include: 001-yum.yml
  tags: ["pkg","common-pkg"]
  when: "ansible_distribution_file_variety == 'RedHat'"


- debug:
    msg: "[BIBIGRID] Generate directory structure available on all hosts"
- import_tasks: 020-disk.yml
  tags: ["disk","common-disk"]

