---
- block:
    - ansible.builtin.debug:
        msg: "[BIBIGRID] Setup common software and dependencies"
    - ansible.builtin.import_tasks: 001-apt.yml
  tags: [pkg, common-pkg]
  when: ansible_distribution_file_variety == 'Debian'

- block:
    - ansible.builtin.debug:
        msg: "[BIBIGRID] Setup common software and dependencies"
    - ansible.builtin.import_tasks: 001-yum.yml
  tags: [pkg, common-pkg]
  when: ansible_distribution_file_variety == 'RedHat'

- ansible.builtin.debug:
    msg: "[BIBIGRID] Generate directory structure available on all hosts"
- ansible.builtin.import_tasks: 020-disk.yml
  tags: [disk, common-disk]
