---
- debug:
    msg: "[BIBIGRID] Configure database"
- include: 006-database.yml
  tags: [database, slurm, master-slurm]
- debug:
    msg: "[BIBIGRID] Setup NFS"
  when:
    - enable_nfs == 'yes'
- include: 010-nfs.yml
  when:
    - enable_nfs == 'yes'
  tags: [master-nfs, nfs]
