---
- ansible.builtin.debug:
    msg: "[BIBIGRID] Configure database"
- ansible.builtin.import_tasks: 006-database.yml
  tags: [database, slurm, master-slurm]
- ansible.builtin.debug:
    msg: "[BIBIGRID] Setup NFS"
  when:
    - enable_nfs == 'yes'
- ansible.builtin.import_tasks: 010-nfs.yml
  when:
    - enable_nfs == 'yes'
  tags: [master-nfs, nfs]
