---
- name: Clean up base images
  hosts: localhost
  vars:
    limit: 1
  vars_files:
    - tags.json

  tasks:
    - ansible.builtin.set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - name: Set images by OS distro and version
      ansible.builtin.set_fact:
        "{{ item.0 }}_{{ item.1.replace('.', '_')  }}_{{ item.2 }}_images": >-
          {{ images.images
           | selectattr('tags', 'search', base_cluster_tag)
           | selectattr('os_distro', '==', item.0)
           | selectattr('os_version', '==', item.1)
           | selectattr('tags', 'search', item.2)
           | selectattr('tags', 'search', 'cluster')
           | sort(attribute='created_at') }}
      loop:
        - [ubuntu, "18.04", master]
        - [ubuntu, "20.04", master]
        - [ubuntu, "22.04", master]
        - [ubuntu, "18.04", worker]
        - [ubuntu, "20.04", worker]
        - [ubuntu, "22.04", worker]
      vars:
        filter: "[?properties.image_type=='image']"

    - name: Clean up old Ubuntu 18 Worker images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_18_04_worker_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_18_04_worker_images | length > limit | int
        - index < ubuntu_18_04_worker_images | length - limit | int

    - name: Clean up old Ubuntu 20 Worker images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_20_04_worker_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_20_04_worker_images | length > limit | int
        - index < ubuntu_20_04_worker_images | length - limit | int

    - name: Clean up old Ubuntu 22 Worker images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_22_04_worker_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_22_04_worker_images | length > limit | int
        - index < ubuntu_22_04_worker_images | length - limit | int


    - name: Clean up old Ubuntu 18 master images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_18_04_master_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_18_04_master_images | length > limit | int
        - index < ubuntu_18_04_master_images | length - limit | int

    - name: Clean up old Ubuntu 20 Worker images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_20_04_master_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_20_04_master_images | length > limit | int
        - index < ubuntu_20_04_master_images | length - limit | int

    - name: Clean up old Ubuntu 22 Worker images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_22_04_master_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu_22_04_master_images | length > limit | int
        - index < ubuntu_22_04_master _images | length - limit | int
