---
- name: Clean up base cluster images
  hosts: localhost
  vars:
    limit: 1
    os_distro: ubuntu
    os_version: 20.04
  vars_files:
    - tags.json

  tasks:
    - ansible.builtin.set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all master base image
      ansible.builtin.shell: >
        openstack image list
        --private
        --tag "base_cluster"
        --tag "cluster"
        --tag "master"
        --property image_type=image
        --property os_version={{ os_version }}
        --property os_distro={{ os_distro }}
        --sort created_at:desc
        -f json
      register: ubuntu_master_images_command
      changed_when: false

    - name: Set master image fact
      ansible.builtin.set_fact:
        ubuntu_master_images: "{{ ubuntu_master_images_command.stdout }}"

    - name: Echo Ubuntu images length
      ansible.builtin.debug:
        var: ubuntu_master_images | length

    - name: Print master Ubuntu images
      ansible.builtin.debug:
        var: item.Name
      loop: "{{ ubuntu_master_images }}"

    - name: Clean up old Ubuntu master {{ os_version }} images
      openstack.cloud.image:
        name: "{{ item.ID }}"
        state: absent
      loop: "{{ ubuntu_master_images }}"
      loop_control:
        index_var: index
      when: ubuntu_master_images | length > limit | int and index >= limit | int

    - name: Retrieve list of all worker base image
      ansible.builtin.shell: >
        openstack image list
        --tag "base_cluster"
        --tag "cluster"
        --tag "worker"
        --property image_type=image
        --property os_version={{ os_version }}
        --property os_distro={{ os_distro }}
        --sort created_at:desc
        -f json
      register: ubuntu_worker_images_command
      changed_when: false

    - name: Set worker image fact
      ansible.builtin.set_fact:
        ubuntu_worker_images: "{{ ubuntu_worker_images_command.stdout }}"

    - name: Echo Ubuntu images length
      ansible.builtin.debug:
        var: ubuntu_worker_images | length
    - name: Print worker Ubuntu images
      ansible.builtin.debug:
        var: item.Name
      loop: "{{ ubuntu_worker_images }}"
    - name: Clean up old Ubuntu {{ os_version }} images
      openstack.cloud.image:
        name: "{{ item.ID }}"
        state: absent
      loop: "{{ ubuntu_worker_images }}"
      loop_control:
        index_var: index
      when: ubuntu_worker_images | length > limit | int and index >= limit | int
