---
- name: Clean up base images
  hosts: localhost
  vars:
    limit: 1
    os_distro: ubuntu
    os_version: 20.04
  vars_files:
    - tags.json

  tasks:
    - ansible.builtin.set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - ansible.builtin.set_fact:
        ubuntu_images: "{{ images.images | selectattr('tags', 'search', base_image_tag)
                          | selectattr('os_distro', '==', os_distro)
                          | selectattr('os_version', '==', os_version)
                          | json_query(filter)
                          | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.image_type=='image']"

    - name: Echo Ubuntu images length
      ansible.builtin.debug:
        var: ubuntu_images | length

    - name: Clean up old Ubuntu {{ os_version }} images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_images }}"
      loop_control:
        index_var: index
      when: ubuntu_images | length > limit | int and index >= limit | int
