---
- name: Cleanup ResEnvs images
  hosts: localhost
  vars:
    limit: 2
  vars_files:
    - tags.json

  tasks:
    - ansible.builtin.set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - ansible.builtin.include_tasks: cleanup_resenvs_images_subloop.yml
      loop:
        - guacamole
        - rstudio
        - theiaide
        - vscode
        - jupyterlab
        - vscode_cwl
      loop_control:
        loop_var: resenv
