---
- name: Clean up base images
  hosts: localhost
  vars:
    limit: 1
    os_distro: ubuntu
    os_version: 20.04
  vars_files:
    - tags.json

  tasks:
    - ansible.builtin.set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all images
      shell: >
        openstack image list
        --private
        --tag "base_image"
        --property os_version={{ os_version }}
        --property os_distro={{ os_distro }}
        --sort created_at:desc
        -f json
      register: ubuntu_images_command


    - name: Set image fact
      ansible.builtin.set_fact:
        ubuntu_images: "{{ ubuntu_images_command.stdout }}"

    - name: Echo Ubuntu images length
      ansible.builtin.debug:
        var: ubuntu_images | length
    - name: Echo Ubuntu images
      ansible.builtin.debug:
        var: ubuntu_images
    - name: Print Ubuntu image names
      ansible.builtin.debug:
        var: item.Name
      loop: "{{ ubuntu_images }}"
    - name: Clean up old Ubuntu {{ os_version }} images
      openstack.cloud.image:
        name: "{{ item.ID }}"
        state: absent
      loop: "{{ ubuntu_images }}"
      loop_control:
        index_var: index
      when: ubuntu_images | length > limit | int and index >= limit | int
