---
- name: Clean up base images
  hosts: localhost
  vars_files:
    - tags.json

  vars:
    os_distro: ubuntu
    os_version: 20.04
    keep_limit: "{{ keep | default(1) | int }}"

  tasks:
    - name: Retrieve list of all images
      openstack.cloud.image_info:
        filters:
          - image_type: image
          - tags:
              - base_image_tag
          - os_distro: "{{ os_distro }}"
          - os_version: "{{ os_version }}"
      register: ubuntu_images

    - name: Echo Ubuntu images length
      ansible.builtin.debug:
        var: ubuntu_images | length

    - name: Clean up old Ubuntu {{ os_version }} images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu_images.images }}"
      loop_control:
        index_var: index
      when: ubuntu_images.images | length > keep_limit and index >= keep_limit
