---
- name: Clean up base images
  hosts: localhost
  vars:
    limit: 1
  vars_files:
    - tags.json

  tasks:
    - set_fact:
        limit: "{{ keep | int }}"
      when: keep is defined and keep | int > 0

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - set_fact:
        ubuntu18_images: "{{ images.image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='1804']"

    - set_fact:
        ubuntu20_images: "{{ images.image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='2004']"

    - name: Clean up old Ubuntu 18.04 images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu18_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu18_images | length > limit | int
        - index < ubuntu18_images | length - limit | int

    - name: Clean up old Ubuntu 20.04 images
      openstack.cloud.image:
        name: "{{ item.id }}"
        state: absent
      loop: "{{ ubuntu20_images }}"
      loop_control:
        index_var: index
      when:
        - ubuntu20_images | length > limit | int
        - index < ubuntu20_images | length - limit | int
