---
- name: Setting up research environment
  hosts: all
  become: true
  gather_facts: true

  vars:
    resenv:
  tasks:
    - name: Include {{ resenv }} variables
      include_vars:
        ansible.builtin.file: ../{{resenv}}/{{ resenv }}_vars_file.yml

    - name: Setting up virtual machine with {{ resenv }}
      import_tasks: ../{{resenv}}/{{ resenv }}.yml
