---
- name: Setting up research environment
  hosts: all
  become: true
  gather_facts: true

  vars:
    bielefeld_mirror_service_exist: false
    resenv: guacamole
  pre_tasks:
    - name: Generic PRE Tasks
      ansible.builtin.import_tasks: ../generic/generic_pre_tasks.yml

  tasks:
    - name: Include {{ resenv }} variables
      ansible.builtin.include_vars:
        file: ../{{ resenv }}/{{ resenv }}_vars_file.yml

    - name: Setting up virtual machine with {{ resenv }}
      ansible.builtin.import_tasks: ../{{ resenv }}/{{ resenv }}.yml

  post_tasks:
    - name: Generic POST Tasks
      ansible.builtin.import_tasks: ../generic/generic_post_tasks.yml
