---
roles:
  - name: oefenweb.rstudio_server
    version: v5.2.0

  - name: oefenweb.latest_r
    version: v3.1.11

  - name: andrewrothstein.miniconda
    version: v6.4.1

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 2.0.0

  - name: andrewrothstein.conda-env
    version: v2.2.0


  - name: geerlingguy.swap
    version: 1.2.0


collections:
  - name: openstack.cloud
    version: 2.4.1

  - name: community.general
    version: 10.7.0


