---
roles:
  - name: oefenweb.rstudio_server
    version: v4.0.0

  - name: oefenweb.latest_r
    version: v3.1.4

  - name: andrewrothstein.miniconda
    version: v6.1.9

  - name: andrewrothstein.conda-env
    version: v2.2.0
  - name: geerlingguy.docker
    version: 6.1.0

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 1.0.8

  - name: geerlingguy.swap

collections:
  - name: openstack.cloud

  - name: community.general
