---
roles:
  - name: oefenweb.rstudio_server
    version: v5.2.0

  - name: oefenweb.latest_r
    version: v3.1.11

  - name: andrewrothstein.miniconda
    version: v6.4.1

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 2.1.0

  - name: andrewrothstein.conda-env

  - name: geerlingguy.swap

collections:
  - name: openstack.cloud
    version: 2.5.0

  - name: community.general