---
roles:
  - name: oefenweb.rstudio_server
    version: v4.1.0

  - name: oefenweb.latest_r
    version: v3.1.7

  - name: andrewrothstein.miniconda
    version: v6.3.1

  - name: geerlingguy.docker
    version: 7.1.0

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 1.7.0

  - name: geerlingguy.swap

collections:
  - name: openstack.cloud
    version: 2.2.0

  - name: community.general
