---
roles:
  - name: oefenweb.rstudio_server
    version: v5.0.0

  - name: oefenweb.latest_r
    version: v3.1.10

  - name: andrewrothstein.miniconda
    version: v6.4.0

  - name: geerlingguy.docker
    version: 7.4.3

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 1.8.7

  - name: andrewrothstein.conda-env

  - name: geerlingguy.swap

collections:
  - name: openstack.cloud
    version: 2.2.0

  - name: community.general
