---
roles:
  - name: oefenweb.rstudio_server
    version: v5.2.0

  - name: oefenweb.latest_r
    version: v3.1.11

  - name: andrewrothstein.miniconda
    version: v6.4.1

  - name: autoscaling
    src: https://github.com/deNBI/autoscaling-ansible
    version: 2.1.0

  - name: andrewrothstein.conda-env
    version: v2.2.0


  - name: geerlingguy.swap
    version: 1.2.0


collections:
  - name: git+https://github.com/openstack/ansible-collections-openstack.git
    version: 2.5.0

  - name: git+https://github.com/ansible-collections/community.general.git
    version: 10.7.0


