- name: Update ResEnv image
  hosts: localhost
  vars:
    resenv: "cwlab"
    location: "bielefeld"
    upload_environment: "staging"
  vars_files:
    - tags.json
    - networks.json

  tasks:
    - set_fact:
        update_18: false
        
    - set_fact:
        update_20: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - set_fact:
        base_images_18: "{{ images.openstack_image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='1804']"

    - set_fact:
        base_images_20: "{{ images.openstack_image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='2004']"

    - set_fact:
        resenv_images_18: "{{ images.openstack_image | selectattr('tags', 'search', vars[resenv + '_tag'])| json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='1804']"  
        
    - set_fact:
        resenv_images_20: "{{ images.openstack_image | selectattr('tags', 'search', vars[resenv + '_tag']) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='ubuntu' && properties.os_version=='2004']"
        
    - set_fact:
        update_18: true
      when:
        - base_images_18 | length > 0
        - resenv_images_18 | length == 0 or
          (resenv_images_18 | length > 0 and (base_images_18 | last).created_at > (resenv_images_18 | last).created_at)
 
    - set_fact:
        update_20: true
      when:
        - base_images_20 | length > 0
        - resenv_images_20 | length == 0 or
          (resenv_images_20 | length > 0 and (base_images_20 | last).created_at > (resenv_images_20 | last).created_at)
          
    - name: Build new {{ resenv }} image - Ubuntu 18
      shell: packer build -var-file=tags.json -var 'os_distro=ubuntu' -var 'os_version=1804' -var 'network={{ vars[location + '_' + upload_environment] }}' ../{{resenv}}/packer_{{ vars[resenv + '_tag'] }}.json
      when: update_18

    - name: Build new {{ resenv }} image - Ubuntu 20
      shell: packer build -var-file=tags.json -var 'os_distro=ubuntu' -var 'os_version=2004' -var 'network={{ vars[location + '_' + upload_environment] }}' ../{{resenv}}/packer_{{ vars[resenv + '_tag'] }}.json
      when: update_20

