---
- name: Update ResEnv image
  hosts: localhost
  vars:
    cluster_type: master
    location: bielefeld
    upload_environment: staging
  vars_files:
    - networks.json

  tasks:
    - name: Set Update Fact to false
      ansible.builtin.set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - name: Get Latest Master Branch Commit
      ansible.builtin.command: git rev-parse --short --verify origin/master
      register: github_hash


    - name: Set Base Images
      ansible.builtin.set_fact:
        base_images: "{{ images.image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Cluster {{cluster_type}} Images
      ansible.builtin.set_fact:
        cluster_images: "{{ images.image | selectattr('tags', 'search', {{cluster_type}})| json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Update facts
      ansible.builtin.set_fact:
        update: true
      when:
        - base_images | length > 0
        - resenv_images | length == 0 or (resenv_images | length > 0 and
            (cluster_images | last).created_at > (cluster_images | last).created_at) or (cluster_images | length > 0
            and (cluster_images | last).github_hash|default ('undefined')  != github_hash.stdout)

    - name: Build new {{ cluster_type }} image - {{ os_distro }} {{ os_version }}
      ansible.builtin.command:
        packer build -var-file=tags.json -var 'os_distro={{ os_distro }}'
        -var 'github_hash={{ github_hash.stdout }}' -var 'os_version={{ os_version }}' -var
        'network={{ vars[location + '_' + upload_environment] }}' ../cluster/{{cluster_type}}/packer_{{cluster_type}}.json
      when: update
