---
- name: Update ResEnv image
  hosts: localhost
  vars:
    resenv: rstudio
    location: bielefeld
    upload_environment: staging
  vars_files:
    - tags.json
    - networks.json

  tasks:
    - name: Set Update Fact to false
      ansible.builtin.set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - name: Get Latest Master Branch Commit
      ansible.builtin.command: git rev-parse --short --verify origin/master
      register: github_hash

    - name: Get md5 Hash from resenv folder
      ansible.builtin.shell:  find ../{{ resenv }} -type f -exec md5sum {} \; | md5sum
      register: md5_hash
    - name: Include {{ resenv }} metadata
      ansible.builtin.command: cat ../{{ resenv }}/{{ resenv }}_metadata.yml
      register: resenv_metadata

    - name: Generate JSON from  {{ resenv }} metadata
      ansible.builtin.copy:
        content: "{{ resenv_metadata.stdout | from_yaml | to_json }}"
        dest: ./{{ resenv }}_metadata.json

    - name: Convert non string json_metadata values to string
      ansible.builtin.script: ../packer/convert_json_values_to_string.py --file ./{{ resenv }}_metadata.json
      args:
        executable: python3

    - name: Set Base Images
      ansible.builtin.set_fact:
        base_images: "{{ images.image | selectattr('tags', 'search', base_image_tag) | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Resens Images
      ansible.builtin.set_fact:
        resenv_images: "{{ images.image | selectattr('tags', 'search', vars[resenv + '_tag'])| rejectattr('tags','search','cluster') | json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Update facts
      ansible.builtin.set_fact:
        update: true
      when:
        - base_images | length > 0
        - resenv_images | length == 0 or (resenv_images | length > 0 and
            (base_images | last).created_at > (resenv_images | last).created_at) or (resenv_images | length > 0
            and (resenv_images | last).md5_hash|default ('undefined')  != md5_hash.stdout)

    - name: Build new {{ resenv }} image - {{ os_distro }} {{ os_version }}
      ansible.builtin.command:
        packer build -var-file=tags.json -var-file=./{{ resenv }}_metadata.json -var 'os_distro={{ os_distro }}'
        -var 'md5_hash={{ md5_hash.stdout }}' -var 'github_hash={{ github_hash.stdout }}' -var 'os_version={{ os_version }}' -var
        'network={{ vars[location + '_' + upload_environment] }}' ../{{resenv}}/packer_{{ vars[resenv + '_tag'] }}.json
      when: update
