---
- name: Update ResEnv image
  hosts: localhost
  vars:
    resenv: rstudio
    location: bielefeld
    upload_environment: staging
  vars_files:
    - tags.json
    - networks.json

  tasks:
    - name: Set Update Fact to false
      ansible.builtin.set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - name: Get Latest Master Branch Commit
      ansible.builtin.command: git rev-parse --short --verify origin/master
      register: github_hash
      changed_when: false

    - name: Get md5 Hash from resenv folder
      ansible.builtin.shell: set -o pipefail &&  find ../generic ../{{ resenv }} -type f -exec md5sum {} \; | md5sum
      register: md5_hash
      args:
        executable: /bin/bash
      changed_when: false

    - name: Include {{ resenv }} metadata
      ansible.builtin.command: cat ../{{ resenv }}/{{ resenv }}_metadata.yml
      register: resenv_metadata
      changed_when: false

    - name: Generate JSON from  {{ resenv }} metadata
      ansible.builtin.copy:
        content: "{{ resenv_metadata.stdout | from_yaml | to_json }}"
        dest: ./{{ resenv }}_metadata.json

    - name: Convert non string json_metadata values to string
      ansible.builtin.script: ../packer/convert_json_values_to_string.py --file ./{{ resenv }}_metadata.json
      args:
        executable: python3

    - name: Set Base Images
      ansible.builtin.set_fact:
        base_images: "{{ images.images
          | selectattr('tags', 'search', base_image_tag)
          | selectattr('os_distro', '==', os_distro)
          | selectattr('os_version', '==', os_version)
          | sort(attribute='created_at') }}"

    - name: Set latest base image name
      ansible.builtin.set_fact:
        latest_base_image_name: "{{ (base_images | last).name }}"

    - name: Set Resens Images
      ansible.builtin.set_fact:
        resenv_images: "{{ images.images
          | selectattr('tags', 'search', vars[resenv + '_tag'])
          | selectattr('os_distro', '==', os_distro)
          | selectattr('os_version', '==', os_version)
          | rejectattr('tags', 'search', 'cluster')
          | sort(attribute='created_at') }}"

    - name: Set Update facts
      ansible.builtin.set_fact:
        update: true
      when:
        - base_images | length > 0
        - resenv_images | length == 0
          or (
          (
          (base_images | last).created_at | to_datetime('%Y-%m-%dT%H:%M:%SZ')
          ) >
          (
          (resenv_images | last).created_at | to_datetime('%Y-%m-%dT%H:%M:%SZ')
          )
          )
          or (
          resenv_images | length > 0 and
          ((resenv_images | last).properties.md5_hash | trim | default('undefined')) != (md5_hash.stdout | trim)
          )

    - name: Build new {{ resenv }} image - {{ os_distro }} {{ os_version }}
      ansible.builtin.command: >
        packer build
          -var-file=tags.json
          -var-file=./{{ resenv }}_metadata.json
          -var "os_distro={{ os_distro }}"
          -var "os_version={{ os_version }}"
          -var "network={{ vars[location + '_' + upload_environment] }}"
          -var "md5_hash={{ md5_hash.stdout }}"
          -var "github_hash={{ github_hash.stdout }}"
          -var "github_token={{ lookup('env', 'GITHUB_REPO_TOKEN') }}"
          -var "source_image_name={{ latest_base_image_name }}"
          ../{{ resenv }}/packer_{{ vars[resenv + '_tag'] }}.json
      when: update
      changed_when: false
