---
- name: Update ResEnv image
  hosts: localhost
  vars:
    resenv: rstudio
    location: bielefeld
    upload_environment: staging
  vars_files:
    - tags.json
    - networks.json

  tasks:
    - name: Set Update Fact to false
      ansible.builtin.set_fact:
        update: false

    - name: Retrieve list of all images
      openstack.cloud.image_info:
      register: images

    - name: Get Latest Master Branch Commit
      ansible.builtin.command: git rev-parse --short --verify origin/master
      register: github_hash

    - name: Include {{ resenv }} metadata
      ansible.builtin.command: cat ../{{ resenv }}/{{ resenv }}_metadata.yml
      register: resenv_metadata

    - name: Generate JSON from  {{ resenv }} metadata
      ansible.builtin.copy:
        content: "{{ resenv_metadata.stdout | from_yaml | to_json }}"
        dest: ./{{ resenv }}_metadata.json

    - name: Convert non string json_metadata values to string
      ansible.builtin.script: ../packer/convert_json_values_to_string.py --file ./{{ resenv }}_metadata.json
      args:
        executable: python3

    - name: Set Base Images
      ansible.builtin.set_fact:
        cluster_base_images: "{{ images.image | selectattr('tags', 'search', 'base')| selectattr('tags', 'search', 'cluster')| selectattr('tags', 'search', 'master')| json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Resens Cluster Images
      ansible.builtin.set_fact:
        cluster_resenv_images: "{{ images.image | selectattr('tags', 'search', vars[resenv + '_tag'])| | selectattr('tags', 'search', 'cluster') | selectattr('tags', 'search', 'master') |  json_query(filter) | sort(attribute='created_at') }}"
      vars:
        filter: "[?properties.os_distro=='{{ os_distro }}' && properties.os_version=='{{ os_version }}']"

    - name: Set Update facts
      ansible.builtin.set_fact:
        update: true
      when:
        - cluster_base_images| length > 0
        - cluster_resenv_images  | length == 0 or (cluster_resenv_images  | length > 0 and
            (cluster_base_images| last).created_at > (cluster_resenv_images  | last).created_at) or (cluster_resenv_images  | length > 0
            and (cluster_resenv_images  | last).github_hash|default ('undefined')  != github_hash.stdout)

    - name: Build new {{ resenv }} image - {{ os_distro }} {{ os_version }}
      ansible.builtin.command:
        packer build -var-file=tags.json -var-file=./{{ resenv }}_metadata.json -var 'os_distro={{ os_distro }}'
        -var 'github_hash={{ github_hash.stdout }}' -var 'os_version={{ os_version }}' -var
        'network={{ vars[location + '_' + upload_environment] }}' ../{{resenv}}/packer_cluster_{{ vars[resenv + '_tag'] }}.json
      when: update
