---
- name: Install java
  ansible.builtin.apt:
    state: latest
    name: default-jre

- name: Install Nextflow
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - nextflow
  remote_user: ubuntu
  become: false
  
- name: Install VSCode Nextflow Lanquage Support Plugin
  ansible.builtin.shell: code-server --install-extension nextflow.nextflow
  args:
    executable: /bin/bash
