---
- name: Install java
  ansible.builtin.apt:
    state: latest
    name: default-jre

- name: Install Nextflow
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - nextflow
  remote_user: ubuntu
  become: false
