---
- name: Install java
  ansible.builtin.apt:
    state: latest
    name: default-jre

- name: Install Nextflow
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - nextflow
  remote_user: ubuntu
  become: false

- name: Install VSCode Nextflow Lanquage Support Plugin
  ansible.builtin.shell: code-server --install-extension nextflow.nextflow --user-data-dir=/home/"{{ vscode_vars.DEFAULT_USER  }}"/.local/share/code-server
  args:
    executable: /bin/bash
