---
- name: Install Snakemake
  pip:
    name: "{{ item }}"
  loop:
    - snakemake
  remote_user: ubuntu
  become: false

- name: Install VSCode Snakemake Lanquage Support Plugin
  ansible.builtin.shell: code-server --install-extension snakemake.snakemake-lang --user-data-dir=/home/"{{ vscode_vars.DEFAULT_USER  }}"/.local/share/code-server # noqa: yaml[line-length]
  args:
    executable: /bin/bash
  remote_user: ubuntu
  become: false
