---
- name: Setup password for default user
  ansible.builtin.user:
    name: "{{ rstudio_vars.default_user }}"
    password: "{{ rstudio_vars.default_password | password_hash('sha512') }}"

- name: Install R role
  include_role:
    name: oefenweb.latest_r
  when: rstudio_vars.create_only_backend == "false"

- name: Install rstudio-server role
  include_role:
    name: oefenweb.rstudio_server
  vars:
    rstudio_install: [r-base]
    rstudio_server_version: "{{ rstudio_vars.RSTUDIO_VERSION }}"
  when: rstudio_vars.create_only_backend == "false"

- name: Copy session file if also installing rstudio
  ansible.builtin.copy:
    content: session-timeout-minutes=180
    dest: "{{ rstudio_vars.RSESSION_FILE_PATH }}"
    mode: "0644"
    owner: root
    group: root
  when: rstudio_vars.create_only_backend == "false"

- name: Flush rstudio handlers
  meta: flush_handlers
  when: rstudio_vars.create_only_backend == "false"
