---
- name: Setup password for default user
  ansible.builtin.user:
    name: "{{ rstudio_vars.default_user }}"
    password: "{{ rstudio_vars.default_password | password_hash('sha512') }}"

- name: Add focal-security repository and install libssl1.1 package
  apt_repository:
    repo: "deb http://security.ubuntu.com/ubuntu focal-security main"
    state: present
    filename: focal-security
  when: os_version == '22.04'

- name: install libssl1.1
  apt:
    name: libssl1.1
    state: present
  when: os_version == '22.04'


- name: Install R role
  include_role:
    name: oefenweb.latest_r
  when: not rstudio_vars.create_only_backend

- name: Install rstudio-server role
  include_role:
    name: oefenweb.rstudio_server
  vars:
    rstudio_install: [r-base]
    rstudio_server_version: "{{ rstudio_vars.RSTUDIO_VERSION | replace('v', '') | replace('+', '-') }}"
  when: not rstudio_vars.create_only_backend

- name: Copy session file if also installing rstudio
  ansible.builtin.copy:
    content: session-timeout-minutes=180
    dest: "{{ rstudio_vars.RSESSION_FILE_PATH }}"
    mode: "0644"
    owner: root
    group: root
  when: not rstudio_vars.create_only_backend

- name: Flush rstudio handlers
  meta: flush_handlers
  when: not rstudio_vars.create_only_backend
