---
- name: Setup password for default user
  become: true
  ansible.builtin.user:
    name: "{{ rstudio_vars.default_user }}"
    password: "{{ rstudio_vars.default_password | password_hash('sha512') }}"
    update_password: always
    password_lock: false

- name: Update package index
  become: true
  apt:
    update_cache: true
  when: not rstudio_vars.create_only_backend

- name: Install apt-file
  become: true
  apt:
    name: apt-file
    state: present
  when: not rstudio_vars.create_only_backend

- name: Install R role
  include_role:
    name: oefenweb.latest_r
  vars:
    r_packages:
      - name: remotes
  when: not rstudio_vars.create_only_backend

- name: Install rstudio-server role
  include_role:
    name: oefenweb.rstudio_server
  vars:
    rstudio_install: [r-base]
    rstudio_server_version: "{{ rstudio_vars.RSTUDIO_VERSION | replace('v', '') | replace('+', '-') }}"
  when: not rstudio_vars.create_only_backend

- name: Install rspm from GitHub
  shell: Rscript -e "remotes::install_github('cran4linux/rspm')"
  
- name: Ensure .Rprofile file exists
  become: true
  file:
    path: /home/{{ rstudio_vars.default_user }}/.Rprofile
    state: touch
  when: not rstudio_vars.create_only_backend
- name: Configure R profile
  become: true
  become_user: ubuntu
  blockinfile:
    path: /home/{{ rstudio_vars.default_user }}/.Rprofile
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      suppressMessages(rspm::enable())
  when: not rstudio_vars.create_only_backend

- name: Install essential system packages
  ansible.builtin.apt:
    name:
      - build-essential
      - libcurl4-openssl-dev
      - libssl-dev
      - zlib1g-dev
      - libpng-dev
      - libjpeg-dev
      - libtiff-dev
      - libfreetype6-dev
      - libfontconfig1-dev
      - libmysqlclient-dev
      - libsqlite3-dev
      - libpq-dev
      - libfribidi-dev
      - libharfbuzz-dev
      - libxml2-dev
      - cmake
    state: present
  become: true

- name: Copy session file if also installing rstudio
  ansible.builtin.copy:
    content: session-timeout-minutes=180
    dest: "{{ rstudio_vars.RSESSION_FILE_PATH }}"
    mode: "0644"
    owner: root
    group: root
  when: not rstudio_vars.create_only_backend

- name: Flush rstudio handlers
  meta: flush_handlers
  when: not rstudio_vars.create_only_backend
