---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip','virtualenv','python3-setuptools']

- name: "Add Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Update apt and install docker-ce"
  apt: update_cache=yes name=docker-ce state=latest

- name: Install additional docker python libraries
  pip:
    name: "{{ item }}"
  loop:
    - docker
    - docker-compose
    - jsondiff
    - pyyaml
  remote_user: ubuntu
  become: false

- name: "Ensure the user ansible_user is part of the docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: "Restart docker and run daemon-reload to pick up config changes"
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker
