- name: Populate service facts
  ansible.builtin.service_facts:

- name: Wait till Apt_Mirror de.NBI Bielefeld Service is done
  ansible.builtin.service_facts:
  until: services['de.NBI_Bielefeld_environment.service'].state == 'stopped'
  retries: 35
  delay: 10
  when: services['de.NBI_Bielefeld_environment.service'] is defined

- name: Disable unattended upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    regexp: ^APT::Periodic::Unattended-Upgrade
    line: APT::Periodic::Unattended-Upgrade "0";
    create: true

- name: Stop apt-daily services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  loop:
    - unattended-upgrades
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer

- name: Wait for dpkg lock
  ansible.builtin.shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ||
          fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      sleep 1
    done
  changed_when: false

- name: Bring system to consistent state
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Fix broken packages (safety net)
  ansible.builtin.command: apt-get -f install -y
  changed_when: false

- name: Install build tools for pip
  ansible.builtin.apt:
    name:
      - build-essential
      - python3-dev
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
