---

- name: Generic POST Tasks
  ansible.builtin.import_tasks: ../generic/generic_post_tasks.yml
- name: POST_TASK  enable unattended upgrades
  ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: ^APT::Periodic::Unattended-Upgrade
        line: APT::Periodic::Unattended-Upgrade "1";
        create: true
- name: POST_TASK Start apt-daily.* systemd services
  ansible.builtin.service:
        name: "{{ item }}"
        state: started
  with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily.timer
