---
- name: Add apt.bi.denbi.de repository key
  ansible.builtin.apt_key:
    url: https://apt.bi.denbi.de/repo_key.key
    state: present


- name: Add apt.bi.denbi.de repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.bi.denbi.de/repos/apt/{{ ansible_distribution_release | lower }} {{ ansible_distribution_release | lower }} main


- name: Update apt cache
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 86400 # One day


- name: Install SimpleVM Metadata Service
  ansible.builtin.apt:
    name: simplevm-metadata-service
    state: present