---
# handlers file for guacamolerdp-ansible

- name: Restart xrdp
  ansible.builtin.systemd:
    name: xrdp
    state: restarted

- name: Restart guacd
  ansible.builtin.systemd:
    name: guacd
    state: restarted

- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat9
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
