name: Ansible Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run ansible-lint
        uses: ansible/ansible-lint@f9364be9c91e7060cd85fca3656879219ea1ae88 # main
